### PR TITLE
Added M3U and Disk control support

### PR DESCRIPTION
**Pull request by DamsRoxxx**
Hello,

I have added M3U file and Disk control support for this core for multi disk games.

Helper functions are in the 'disc_control.h' and 'disc_control.c' (for reusability). Makefile have been updated to build them.

The readme have also been updated to the markdown format.

Let me know if there is problems.

DamsRoxxx

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks a lot for this!

**Comment by twinaphex** [comment]
Hi there,

it no longer compiles now for WiiU.

http://p.0bl.net/34513

dirname() is not portable, I hope you can use something else instead. I'd suggest building up the base directory in retro_load_game (you would have info->path then which would be the full pathname), and then use that base directory later on in your disk_control.c file.

**Comment by DamsRoxxx** [comment]
Hi,

Ok, good solution and more portable.

I will use info->path and get rid of dirname to fix the issue.

Thanks for the suggestion.

**Comment by DamsRoxxx** [comment]
In fact, I already use the full path provided by info->path. 

It is copied in global RPATH in wich I use.

I will find another solution...

**Comment by twinaphex** [comment]
Let me know when you have a fix for this. Currently RetroArch WiiU does not compile in its entirety as a result of this, so the sooner the better..

**Comment by DamsRoxxx** [comment]
I rewrote a dirname equivalent from scratch.

I submitted a patch in a new pull request.

I hope it will now build and work on WiiU.

Let me know.

**Pull request merged**
