### PR TITLE
Disable GUI core option

### PR DESCRIPTION
**Pull request by hiddenasbestos**
Adds a core option to enable/disable GUI shortcuts F9 and F10.

### CODE REVIEW

**Comment by DSkywalk** [comment]
I am redone completly the GUI, anyway Fx are unused in emulation, Why do you want disable it?

**Comment by hiddenasbestos** [comment]
Hi, I don't think the GUI should be there at all so this is a bit of a compromise really. The front end should be doing any GUI work imo. Happy for this to remain unmerged as a no-GUI build isn't possible atm.

Also for me in the case of V.Keyboard > PG2 > Exit   it risks taking down the F-E with data loss. Not a big issue for RetroArch, a big problem for Grid Cartographer.

**Comment by DSkywalk** [comment]
> Hi, I don't think the GUI should be there at all so this is a bit of a compromise really. The front end should be doing any GUI work imo. Happy for this to remain unmerged as a no-GUI build isn't possible atm.

I'm totally agree with you.

> Also for me in the case of V.Keyboard > PG2 > Exit it risks taking down the F-E with data loss. Not a big issue for RetroArch, a big problem for Grid Cartographer.

If you want PR this, i'm agree with your point.

Thanks for your help, @hiddenasbestos :+1:

**Comment by DSkywalk** [comment]
gridcartographer.com it looks great! :dancer:

**Comment by r-type** [comment]
I agree that RA should provide the ability to make the core buitin GUI , but unhappily it's not the case with libretro api.
Anyways, i see this port despite the new emulation enhancment take a direction that I do not endorse,
in the fact of removing the gui part. I hope DSkywalk, you will still leave an Gui in this core and if not it will be a problem for me. and if you do so , i hope you will dicuss here about it before  you drop theexistent one.

Consedering all this ,I prefere for the moment to turn towards Colin Pitrat version,
as it as a builtin GUI using wGui and SDL and is highly heavily maintained.

Using my libretro-sdl implementation the port is simple enough (just 2/3 minor code modification)

 
caprice32


cap32colin

**Comment by DSkywalk** [comment]
You have ignored this core for years and now we have: saves-states, hires mode, netplay, 3DS core compatible, keyboard working like a charm,... and your problem is if I remove the filemanager. Seriouslly?

Anyway...
> ... in the fact of removing the gui part

who wants to remove **your GUI**?
I want remove duplicates and document it. Only to be maintainable by humans.

>... turn towards Colin Pitrat version

We are almost synced with Colin (except his UI).

> I prefere for the moment to turn towards Colin Pitrat version,

Yep, your solution is great. Create a new core and leave it in a few weeks... :+1: 
Even some MSX users asked me if I can contribute in their fMSX core. 

What good are so many cores if nobody cares for them?

I hope the decision the create another core (or remove) depends on @twinaphex or any other member. Because it is the first time I see someone with your conduct in an **opensource** project.

**Comment by r-type** [comment]
>>>>You have ignored this core for years and now we have: saves-states, hires mode, netplay, 3DS core compatible, keyboard working like a charm,... and your problem is if I remove the filemanager. Seriouslly?

Great and  sorry I do not have any more medals on me.
And Yes my problem is if you remove a feature like GUI without re add it .

I 'll try to be more precise , i ok with the fact you don't like the gui i wrote , i'm also agree with if you change the GUI core to another GUI core , if it as improvement. I'am not a defender of the nuklear Gui.
It's not my Gui , i hook it to this core to at least have one ,Great if you plan tp change it for imgui or some libs like that.

That said :

>>>>We are almost synced with Colin (except his UI).

So what the purpose of this core . if it aim to be a clone of Colin one except for UI.


>>>>Yep, your solution is great. Create a new core and leave it in a few weeks... +1
Even some MSX users asked me if I can contribute in their fMSX core.

I think i have quite contributed here over years for not having to justify myself with you,

BTW  the fmsx core was completly rewrite but someone else so if you look at the contributors you will not see my name, i don't understand  what are you trying to prove here.

>>> What good are so many cores if nobody cares for them?

Hey ,I care them and use them , and that's enough to justify them for me!

>>>> I hope the decision the create another core (or remove) depends on @twinaphex or any other member. Because it is the first time I see someone with your conduct in an opensource project.

Ho nice guy, you will now cry so that someone from here prevents me from creating a new core.
Me ,it's the first time I see this too.

BTW ,if @twinaphex or other libretro administrators think like you and absolutely want to prevent me for creating a new core under the libretro repository , i agree and don't mind,
remove the rights I have on all the libretro deposits. maybe it is time for me to definilty leave this place.

**Comment by DSkywalk** [comment]
Sorry @hiddenasbestos 

We wait your "V.Keyboard > PG2 > Exit" PR :+1: 

Thanks!

**Comment by hiddenasbestos** [comment]
One of this things the GUI is needed for is management of the drives. Since the current LibRetro spec isn't great for this, I've designed a new API which might help. Please read: https://github.com/libretro/libretro-common/issues/108 and I welcome any feedback!

**Pull request closed without merging**
