### PR TITLE
added hires video mode and allowed 16bpp compiles.

### LINKED ISSUE #26: Mode 2 graphical artefacts
In Mode 2, the subpixel colours are not rendered correctly, making text unreadable. It does not appear to affect the blue channel.

I could not replicate this bug with standalone Caprice32 from https://github.com/ColinPitrat/caprice32.git

Sample BASIC program to replicate:
1 REM Hit Enter to cycle through pen 1 colours
10 S$="Pack my box with five dozen liquor jugs"
20 i=0
30 ON BREAK GOSUB 100
40 MODE 2
50 INK 1,i
60 PRINT UPPER$(S$):PRINT LOWER$(S$)
70 WHILE INKEY(18)<0:WEND
80 i=i+1:IF i>26 THEN GOTO 100
90 GOTO 50
100 MODE 1

### PR DESCRIPTION
**Pull request by DSkywalk**
Hello!

I try to make a PR with minimal code changes, just added hires modes and 16bpp for classics consoles.
This PR fixes #26 

Thanks :tada:

### CODE REVIEW

**Comment by DSkywalk** [comment]
current implementation just allows lowres, if you change the video mode...
imagen

with pr and using 768x544 internal resolution, you get hires mode working like a charm :+1: 
imagen

**Comment by r-type** [comment]
cool , quick review of the code and seems ok,
but let me time to test.

**Comment by r-type** [comment]
Ok first part is to move 
```
//#define RENDER16B
//#undef RENDER16B
#ifdef RENDER16B
#define M16B
#endif
```
from libretro-core.c to libretrocore.h else nuklearui will not be aware if we using 16BITmode ,
it prevent the crash. but still missing text.

**Comment by DSkywalk** [comment]
Sorry, i forget to test GUI in my NES.mini :(
A take a look :+1:

**Comment by DSkywalk** [comment]
Ok, print is missed in 16bit mode
nuklear_retro_soft.h 
https://github.com/libretro/libretro-cap32/blob/master/libretro/nukleargui/retro/nuklear_retro_soft.h#L246

Working on it!

**Comment by DSkywalk** [comment]
Done, ready for review :+1:

**Comment by r-type** [comment]
sorry was off yesterday!
seem ok now.

**Comment by DSkywalk** [comment]
np, really thanks @r-type

**Pull request merged**
