### PR TITLE
Remove unused joystick from input descriptor

### PR DESCRIPTION
**Pull request by garbear**
Only port 0 of struct `amstrad_devices` is accessed (see https://github.com/libretro/libretro-cap32/search?utf8=✓&q=amstrad_devices).

Also, `input_state_cb` is only called with port 0. Search [nuklear_retro_soft.h](https://github.com/libretro/libretro-cap32/blob/master/libretro/nukleargui/retro/nuklear_retro_soft.h) for `input_state_cb`.

### CODE REVIEW

**Comment by garbear** [comment]
Disregard this, I missed this line: https://github.com/libretro/libretro-cap32/blob/3e14cebabb3d58dd33990158a2379f3759975409/libretro/nukleargui/app.c#L412

Maybe we should modify the input descriptor to only report joystick support? It seems that cap32 assumes a keyboard is always present.

**Comment by r-type** [comment]
wait a minute ! 
you are wrong,  we are polling for player 2 
https://github.com/libretro/libretro-cap32/blob/master/libretro/nukleargui/app.c#L412

oh i miss your last comment :)

**Comment by r-type** [comment]
no it doest assume kbd is always present!
we can inhibit it to not conflict with joystick binding using keyboard.
 please don't remove stuff you don't understand ,ask before

**Comment by garbear** [comment]
I'm asking now. Where is RETRO_DEVICE_AMSTRAD_KEYBOARD used? If no code checks if this subclass has been specified, do we still need it?

**Comment by r-type** [comment]
it will be used to permit the keymapper stuff

**Comment by garbear** [comment]
What is the keymapper stuff? Is this joystick-to-keyboard or keyboard-to joystick mapping? Does the mapping take place in the frontend or the core?

**Comment by r-type** [comment]
it is keyboard-to joystick mapping
https://github.com/libretro/vice-libretro/issues/7
see fr500 comment , the constraint is the input device has to be RETRO_DEVICE_KEYBOARD or a subclass of it.

**Comment by fr500** [comment]
It's a frontend feature, pretty much like CORE INPUT REMAPPING

**Comment by garbear** [comment]
Am I correct in thinking the libretro API has two keyboard interfaces? An event-based on via `RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK` and a poll-based one via `RETRO_DEVICE_KEYBOARD`?

I have encountered several cores that use the event-based keyboard API, but Caprice32 is the first one I've encountered that uses the poll-based one. It seems that these two APIs conflict with each other, and thus the `RETRO_DEVICE_KEYBOARD` workaround. Should we add a way for the core to select poll-based or event-based keyboard input?

**Comment by r-type** [comment]
i 've used poll based method in most of core port i've done (mame,puae,vice,cap32,px68,atari800,hatari ect ..)

i never heard about such conflict ...the rule is to not enable the two in same time .

btw callback method is not enable in cap32 

https://github.com/libretro/libretro-cap32/blob/master/libretro/libretro-core.c#L850
https://github.com/libretro/libretro-cap32/blob/master/libretro/libretro-core.c#L824

here is an old attempt to do such thing (choose polling method / callback) by a core option.
https://github.com/r-type/dosbox-libretro/commit/c92fee9bc4d30dfe2a104e2de2608cc44e740db5

**Comment by garbear** [comment]
Poll-based keyboard input requires the frontend to hold a large state (320 keys for cap32). I can certainly implement this in my frontend, but it seems silly to have to separate keyboard APIs. If I don't want my frontend to waste 320 bytes for a feature that's not used, the core should communicate that it doesn't need the frontend to maintain state. Is this something we can add to the libretro API?

**Comment by fr500** [comment]
Yes there are two APIs and you don't really need to set device to RETRO_DEVICE_KEYBOARD to get either of them to work.

Basically keyboard input "always works", guess it's a shortcoming of the API (and it doesn't really seem a good fit to be hooked up in an input port).

You should have only one of them hooked up in a core.

**Comment by garbear** [comment]
I don't think connecting the keyboard to an input port is a good fit. Keyboards are always assumed to be connected and do not exclude joysticks on the joystick port. If setting this isn't necessary, and it only serves to break joysticks, should it be removed from the core?

**Comment by fr500** [comment]
I don't see how it breaks joysticks..
It's the only way we can signal the frontend right now we want to use the key mapper

**Comment by garbear** [comment]
Shouldn't the use of a keymapper be entirely up to the frontend? The core shouldn't care if its joystick input comes from a keyboard or a joystick or a physical arcade cabinet, that's the purpose of the RetroPad. Using `RETRO_DEVICE_KEYBOARD` to indicate a keymapper breaks this abstraction.

If a port can only be a joystick or a keyboard, how do you specify a keyboard plus two joysticks? What is the effect of connecting a keyboard to port 2 instead of port 1?

**Comment by fr500** [comment]
I didn't say it's perfect, it's what we have now, that's it.

Problem is, even if we just had the keymapper always enabled there is no way to unmap buttons from the retropad so some buttons would always be inaccessible or conflicting with the keymapper.

I actually have been thinking about having an environment callback so the core can request keymapper support. That would allow you to have joypads attached and the keymapper still enabled but then someone has to code the frontend functionality and a sensible GUI for all that.

**Comment by fr500** [comment]
FWIW what I've done (as a user) for my DOS games is use retropad in port 1 and keymapper in port 2 
Then I just set my physical gamepad to port 1 or port 2 accordingly.

(RetroArch itself lends itself nicely for this scenario, not sure about RetroPlayer)

**Comment by garbear** [comment]
I'm confused with how RetroArch does it. With RetroPlayer, the GUI reflects the hardware you're configuring instead of the RetroPad abstraction. It assigns the keyboard and mouse to player 1, but does not exclude the joystick from either player:

dos hubs

By using polling here, the keyboard excludes the joystick from the port (or maybe it doesn't? this isn't specified and as you said may be dangerous).

I either need to propagate this limitation up from the core to my GUI, or fix the limitation in Caprice32. Event-based keyboard input doesn't consume a joystick port, and it has the advantage of not requiring the keyboard state to be maintained in both the frontend and core. Maybe we should switch to this? The only thing we'd have to do is move the keyboard state into the core.

**Comment by fr500** [comment]
I have never used this core so I'm not sure. I also don't understand the "hardware you're configuring instead of the retropad abstraction part"

I'm using a DS3 here, here is how it looks for my player 2:

image

In dosbox we use the SET_KEYBOARD callback and keyboard is always active you're right, so probably that would be better suited for you, but I really can't tell you what to do here.

**Comment by r-type** [comment]
Personally , I prefer use the polling method (and also i don't want to switch to callback method in all other core I've mentioned before).
concession can be done to implement the two method (poll/cb) and let user choose by a core option.
But certainly not remove the polling method

**Comment by fr500** [comment]
I am still not 100% clear of what the problem is to be honest
I think the problem is that using the keyboard means you have to lose a "controller port"?

**Comment by garbear** [comment]
Right, and I either have to propagate this limitation from the core to the GUI or fix caprice to not lose a controller port.

**Comment by fr500** [comment]
I just tested bluemsx (in RetroArch) and keyboard inputs are still responding but it could be a buggy core
What do I need to test this core?

**Comment by garbear** [comment]
All cores I've tested has working keyboard input. I haven't tested this core yet, I'm still working on supporting its configuration in the GUI. It's the first core I've encountered that excluded joysticks from ports with keyboards attached.

**Comment by r-type** [comment]
if it's a buggy core ,yes we have and will fix it , but i repeat we will not remove the polling input method just because you want.

**Comment by fr500** [comment]
dosbox and bluemsx are like this too.
@r-type I meant bluemsx is buggy :p

**Comment by fr500** [comment]
BTW I'm actually here trying to find a solution that suits everyone

**Comment by r-type** [comment]
@garbear  you should then have the same problem with vice core.
@fr500  I know :+1: 

So the point is how have key mapper working using poll input method and satisfy RetroPlayer requirement

**Comment by fr500** [comment]
Ok so how about this for a "gentleman's agreement"

- Physical KBD / Mouse always ON
- When the ports are set to RETRO_DEVICE_KEYBOARD gamepad input on that port is disabled

That should work for everyone.

**Comment by garbear** [comment]
Nice solution. It looks like this would work. Should this be clarified in the API?

**Comment by r-type** [comment]
yes that sound good! and yes it will be nice to clarify this in the API.
also an sample in libretro-samples that show the good way to implement this could be an good idea.

**Comment by fr500** [comment]
I think clarifying in the API may be a bit too soon, basically we're trying to define undefined behavior now. Let's see how it evolves in both sides of the fence and maybe then we can submit a PR that defines the intended behavior

**Comment by garbear** [comment]
Sounds good. It looks there's an issue, gamepads are disabled using `RETRO_DEVICE_KEYBOARD` if there's a keyboard attached, and `RETRO_DEVICE_NONE` if there's no keyboard. This conflicts with our assumption that a keyboard is always attached. I've added a way to specify if a keyboard is connected/disconnected in RetroPlayer. Maybe the libretro API needs something similar?

I'll hack on this a while and let you know what I come up with.

**Comment by fr500** [comment]
RETRO_DEVICE_NONE honored means nothing is plugged in the port but KBD input should still work.
Basically we're neglecting RETRO_DEVICE_KEYBOARD for keymapper use.

**Comment by fr500** [comment]
Goals:

Define how KBD / Mouse should work in cores

- Physical KBD / Mouse always should work (in cores that require KBD and Mouse)
- When the ports are set to RETRO_DEVICE_KEYBOARD gamepad input on that port is disabled so a frontend can dedicate that port to KeyMapper input (if implemented)
- RETRO_DEVICE_NONE should always be honored (meaning the PORT is disconnected, physical keyboard is always enabled so it should still work)

**Comment by fr500** [comment]
Sounds good?

**Comment by r-type** [comment]
yes for me.

**Comment by garbear** [comment]
Can `RETRO_DEVICE_NONE` serve the purpose of `RETRO_DEVICE_KEYBOARD`? Both mean the port has no gamepad, so it seems silly to duplicate the constants.

I disagree about keyboards always being connected. It would be nice if a core could specify it doesn't use the keyboard so the frontend doesn't have to waste putting 320 keys in the heap.

I actually package an XML tag with our libretro cores called "<supports_keyboard>" that I have to manually scrape from each core's source. If we add a flag to the libretro API we can accomplish this goal and remove a maintenance burden at the same time.

**Comment by fr500** [comment]
well the constants are already part of the API and we can't just remove them.
Then maybe we should honor RETRO_DEVICE_NONE completely? (no inputs work at all)

It's fine by me.

**Comment by r-type** [comment]
Sorry but I'm elsewhere now. I let you discuss about the rest.

 (@fr500 not related,  I've found that the input pointer on wiiu not working anymore with recent RA , spent 2h to debug a core then try an old RA and realize that pointer working fine with it)

**Pull request closed without merging**
